### ISSUE TITLE
[NIAttributedLabel] is not friendly for emoticons

### ISSUE THREAD

**Issue by NathanLi** [jverkoey/nimbus#519]
![443a5e81-6db3-40c9-98c8-e16745694930](https://f.cloud.github.com/assets/4445948/2242551/b8c26d5c-9d06-11e3-8d47-ffaa4a4b67ea.png)
When insert the emoticons, the line space is incorrect.

**Comment by Shebuka** [comment]
Have the same problem here. And using NISizeOfAttributedStringConstrainedToSize gives worser result that standard sizeWithFont. The height is smaller that is needed and last line is cut away either with or without emoji.

**Comment by menegola** [comment]
@Shebuka which attributes have you set in the attributed string that makes NISizeOfAttributedStringConstrainedToSize not to work properly?
