### ISSUE TITLE
[attributedlabel] Kerning bug when using the text property on NIAttributedLabel

### ISSUE THREAD

**Issue by stephanemoore** [jverkoey/nimbus#543]
I haven't fully diagnosed this bug but it seems like kerning can break if you use the text property on NIAttributedLabel? Will provide an update after I investigate more.

**Comment by mwyman** [comment]
`NIAttributedLabel -setText:` always sets the kerning attribute on its internal attributed string to the value of its `textKern` property; `textKern` has a default value of 0, which disables kerning.

There is currently no way to use the `NIAttributedLabel` `.text` property and get default kerning.
