### ISSUE TITLE
nitoolbarphotoviewcontroller/NIPagingScrollView issue

### ISSUE THREAD

**Issue by harveyB** [jverkoey/nimbus#580]
hi,

when using in iPhone with scrubber disabled, there is a bug:

the user is able to scroll/page horizontally since it uses the NIPagingScrollView, but this page scrolling is broken in that it changes the photo sometimes and at other times it freezes without moving the photo to next or previous - on iPhone6 it seems to always work, but on iPhone5 it freezes most of the time.

**Comment by KenYuan1987** [comment]
Try to set _scrollView.scrollEnabled = NO; in NIPhotoScrollView.It works fine for me.
