### ISSUE TITLE
NINetworkImageView.m:360:50: Incompatible block pointer types sending 'void (^)(NSUInteger, NSInteger, NSInteger)' to parameter of type 'void (^)(NSUInteger, long long, long long)'

### ISSUE THREAD

**Issue by jackyyip** [jverkoey/nimbus#601]
NINetworkImageView.m:360:50 defines the setDownloadProgressBlock as:
^(NSUInteger bytesRead, NSInteger totalBytesRead, NSInteger totalBytesExpectedToRead)

However, AFNetworking 2.5.2 expects:
(void (^)(NSUInteger bytesRead, long long totalBytesRead, long long totalBytesExpectedToRead))

This is causing a compiler error (as stated in the title of the issue).

**Comment by elsurudo** [comment]
:+1: on this
