### ISSUE TITLE
Wants to be updated podspec's version to 1.2.1 from 1.2.0.

### ISSUE THREAD

**Issue by yshrkt** [jverkoey/nimbus#604]
I hope you to be updated podspec's version to 1.2.1 from 1.2.0.

**Comment by mave99a** [comment]
+1

**Comment by gelosie** [comment]
+1

**Comment by squarezw** [comment]
+1

**Comment by jjangg96** [comment]
+1

**Comment by wonderffee** [comment]
+1
pod search Nimbus
-> Nimbus (1.2.0)
   An iOS framework whose growth is bounded by O(documentation).
   pod 'Nimbus', '~> 1.2.0'
   - Homepage: http://nimbuskit.info
   - Source:   https://github.com/jverkoey/nimbus.git
   - Versions: 1.2.0, 1.0.0, 0.9.3, 0.9.2, 0.9.1, 0.9.0 [master repo] - 1.2.0, 1.0.0, 0.9.3, 0.9.2,
   0.9.1, 0.9.0 [master-1 repo]

**Comment by wonderffee** [comment]
Can someone tell me how to load nimbus from local repository? I just have no idea about the path of podspec file.

**Comment by jverkoey** [comment]
Finally cut 1.3.0: https://github.com/CocoaPods/Specs/blob/6271aef2a25db55fa8f161965d10a7731637d886/Specs/Nimbus/1.3.0/Nimbus.podspec.json
