### ISSUE TITLE
Pods/Nimbus/src/core/src/NIButtonUtilities.m:23:18: Too many arguments to function call, expected 0, have 3

### ISSUE THREAD

**Issue by ahjin** [jverkoey/nimbus#611]
I am use Nimbus (1.2.0).
Why is it so?  previous versions are not.

**Comment by ahjin** [comment]
objc_msgSend without a typecast is usually an error  
Recommended build setting for strict checking

Build Setting -> Apple LLVM 6.0 - Preprocessing -> Enable Strict Check for objc_msgSend Call -> No

**Comment by aelam** [comment]
pod use :head  instead

发自我的 iPhone

**Comment by thanhhh** [comment]
> Build Setting -> Apple LLVM 6.0 - Preprocessing -> Enable Strict Check for objc_msgSend Call -> No
It's not worked. Do you have any solution?

**Comment by ahjin** [comment]
I can do it.
You must selected Nimbus target in pod project, then do those step.

**Comment by vani2** [comment]
Enable Strict Check for objc_msgSend Call works well 👍
