### ISSUE TITLE
NINetworkingImageView failing build

### ISSUE THREAD

**Issue by Liron-K** [jverkoey/nimbus#612]
Updated to :head and I'm getting the following error when trying to build:
NINetworkImageView.m:360:50: Incompatible block pointer types sending 'void (^)(NSUInteger, NSInteger, NSInteger)' to parameter of type 'void (^)(NSUInteger, long long, long long)'

**Comment by Liron-K** [comment]
This seems to be because I was on AFNetworking 2.5.4 and not 2.1

**Comment by wonderffee** [comment]
Just avod using NINetworkImageView.
Use nimbus as follows:
pod 'Nimbus/Core', :head
pod 'Nimbus/Launcher', :head
pod 'Nimbus/AttributedLabel', :head
