### ISSUE TITLE
problem with NIButtonUtilities when integrate using CocoaPods

### ISSUE THREAD

**Issue by hpsoar** [jverkoey/nimbus#616]
the latest CocoaPods version  refers to tag 1.2.0,

however,  I found both tag 1.2.0, 1.2.1 have the issue with 

IMP method = [target methodForSelector:selector];

can someone help with this?

**Comment by aelam** [comment]
use :head


发自我的 iPhone

**Comment by wonderffee** [comment]
Use nimbus as follows:
pod 'Nimbus/Core', :head
pod 'Nimbus/Launcher', :head
pod 'Nimbus/AttributedLabel', :head

**Comment by Stunner** [comment]
@wonderffee thanks! :+1:
