### ISSUE TITLE
pod version

### ISSUE THREAD

**Issue by Muscliy** [jverkoey/nimbus#626]
i found the project version is 1.2.1 but pod version only less than 1.2.0, the version 1.2.0 has some issues in arm 64 , please update pod version to 1.2.1

**Comment by jverkoey** [comment]
Finally cut 1.3.0: https://github.com/CocoaPods/Specs/blob/6271aef2a25db55fa8f161965d10a7731637d886/Specs/Nimbus/1.3.0/Nimbus.podspec.json
