### ISSUE TITLE
Bundle resources not loaded by cocoapods

### ISSUE THREAD

**Issue by valeriomazzeo** [jverkoey/nimbus#633]
I believe this:

```
    s.resource_bundles = {
      'WebController' => ['src/webcontroller/resources/NimbusWebController.bundle/*']
    }
```

should be this instead:

```
    s.resource_bundles = {
      'WebController' => ['src/webcontroller/resources/NimbusWebController.bundle']
    }
```

That cause cocoapods not to be able to load correctly the bundles for the overviewer and the web controller resources.

Maybe there is also a typo here: `s.resource_bundles = {` instead than `ss.resource_bundles` ?

**Comment by vixentael** [comment]
i think, @valeriomazzeo you're right in your assumptions.
i've created podspec according to your changes https://gist.github.com/vixentael/795022ea86213e1e4a2d
it can be used like
```
pod 'Nimbus', :podspec => 'https://gist.githubusercontent.com/vixentael/795022ea86213e1e4a2d/raw/b826b802c21fd4d8013a05372a597733c0559233/Nimbus_1.3.0.podspec'
```

despite the fact that bundle is loaded, webcontroller still cannot load back and forward icon images. i'm not sure if [`NIPathForBundleResource`](https://github.com/jverkoey/nimbus/blob/73167413a1636a026431c1649e4a8c0fe26ee2c9/src/core/src/NIPaths.m#L25) is working fine.

**Comment by valeriomazzeo** [comment]
That maybe bevande those are not in the main bundle and Nimbus doesn't call bundle with class?
