### ISSUE TITLE
Find alternatives to deprecated -attributedLabel:shouldPresentActionSheet:withTextCheckingResult:atPoint:

### ISSUE THREAD

**Issue by Arcank** [jverkoey/nimbus#635]
UIActionSheet is deprecated in iOS 8.3. When building, this warning is issued:
src/attributedlabel/src/NIAttributedLabel.h:161:88: warning: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead [-Wdeprecated-declarations]

**Comment by Arcank** [comment]
Following https://github.com/jverkoey/nimbus/commit/c8e4c41caf71df12ae869f1bf9cc4c8b3fbfc4a8, `-attributedLabel:shouldPresentActionSheet:withTextCheckingResult:atPoint:` is deprecated. We should propose alternatives for clients.

**Comment by Arcank** [comment]
@stephanemoore : what are the alternatives?

**Comment by stephanemoore** [comment]
I think #689 provides a reasonable alternative.
