### ISSUE TITLE
 Three20 Migration guide link broken

### ISSUE THREAD

**Issue by lferro9000** [jverkoey/nimbus#645]
Just a note that the link at the bottom of the Readme regarding the article about the migration from Three20 is broken.

**Comment by elburro1887** [comment]
http://wiki.nimbuskit.info/Add-Nimbus-to-your-project

is also broken.

**Comment by nvisionvictor** [comment]
http://wiki.nimbuskit.info/Three20-Migration-Guide

Also still broken as well as other documentation links.

**Comment by KevinTurnbull** [comment]
To be precise - it looks like the whole wiki.nimbuskit.info ruby server is crashed. 

There was a post by @jverkoey  that stated that if the sites went down again (made in 2014) that he would need to restart the server to get them running again. 

With the newest version of iOS killing three20 for good it'd be helpful to have the migration guide back up agian.

**Comment by jverkoey** [comment]
The website mirrors the GitHub wiki: https://github.com/jverkoey/nimbus/wiki/Three20-Migration-Guide

**Comment by KevinTurnbull** [comment]
You sir are a hero and a gentleman.
