### ISSUE TITLE
NIQueryDictionaryFromStringUsingEncoding uses iOS 9 deprecated API

### ISSUE THREAD

**Issue by Arcank** [jverkoey/nimbus#649]
NIQueryDictionaryFromStringUsingEncoding uses stringByReplacingPercentEscapesUsingEncoding which is deprecated in iOS 9.
It is advised to replace it with stringByRemovingPercentEncoding, using UTF-8 as the encoding.

If Nimbus doesn't target pre-iOS 7, it could be replaced, and NIQueryDictionaryFromStringUsingEncoding would become NIQueryDictionaryFromString.

Any advice? Is there a deprecation process?

**Comment by johosher** [comment]
+1

**Comment by Arcank** [comment]
iOS 8 is the supported base SDK: https://github.com/jverkoey/nimbus/commit/81b9cd92595c8641754ed921a86d8d3ad5ebe190.
