### ISSUE TITLE
when can support AFNetworking3.0

### ISSUE THREAD

**Issue by itechsen** [jverkoey/nimbus#665]
Just like "NINetworkImageView" it use AFNetworking 'api in v2.6. But 3.0 will be the trend of the future

**Comment by baixiaotian1abc** [comment]
yeah

jack  in  China
it_server007@outlook.com<mailto:it_server007@outlook.com>



在 2016年11月16日，下午2:18，TechSen <notifications@github.com<mailto:notifications@github.com>> 写道：

Just like "NINetworkImageView" it use AFNetworking 'api in v2.6. But 3.0 will be the trend of the future
