### ISSUE TITLE
无法正常编译

### ISSUE THREAD

**Issue by zuqiu123** [jverkoey/nimbus#686]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/15611129/43443187-bf1a6eac-94d2-11e8-9e96-3dfc04f890f7.png">

**Comment by zuqiu123** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/15611129/43443240-e3416286-94d2-11e8-8ce1-3e7bd3739c71.png">
afn和一些分类缺失

**Comment by NicholasPaul777** [comment]
你哪位？什么项目？
________________________________
发件人: zuqiu123 <notifications@github.com>
发送时间: 2018年7月31日 7:04
收件人: jverkoey/nimbus
抄送: Subscribed
主题: Re: [jverkoey/nimbus] 无法正常编译 (#686)


[image]<https://user-images.githubusercontent.com/15611129/43443240-e3416286-94d2-11e8-8ce1-3e7bd3739c71.png>

afn和一些分类缺失

―

**Comment by zuqiu123** [comment]
你好就是这个框架,直接下载解压的

**Comment by zuqiu123** [comment]
你好就是这个框架，直接下载解压的
