### ISSUE TITLE
Apple generates warnings for submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by JinfengLi888** [jverkoey/nimbus#713]
I've received this warning from Apple. Can our devs pay attention to this issue and remove uiwebview from our project?

From Apple:

Dear Developer,We identified one or more issues with a recent delivery for your app, Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.After you've corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

**Comment by stephanemoore** [comment]
Are you using `NIWebController`?

**Comment by JinfengLi888** [comment]
@stephanemoore I'm not using NIWebController but our project calls UIWebView API. That's the problem. We need to stop calling UIWebView API no matter you actually use it to show web view or not.

**Comment by vrmanepalli** [comment]
@stephanemoore thank you for responding to @JinfengLi888. I am also facing this and wish to know your plans on addressing this. 
Do you happen to know how soon we can expect the upgrade? Any dependencies? Road blocks?
I look forward hearing from you.
Thanks.

**Comment by jverkoey** [comment]
I've sent out https://github.com/jverkoey/nimbus/pull/715 to annotate NIWebController as deprecated. We will not be adding support for WKWebView and will instead be deleting this API from Nimbus.

**Comment by JinfengLi888** [comment]
@jverkoey Even thought you marked NIWebController as deprecated, that didn't solve the problem because the project still calls UIWebView API. I think you might need to remove NIWebController from the project, not just mark it as deprecate.

**Comment by vrmanepalli** [comment]
@jverkoey are the efforts to make a minor release by deleting UIWebView (Not depreciating), is in progress? Please share the timeline.
Thanks.

**Comment by stephanemoore** [comment]
Note that I have not heard any reports of apps actually being rejected for linking against UIWebView. The reports that I have heard are that Apple will generate a warning for apps that link against UIWebView. We should still address the UIWebView references in some fashion but it doesn't seem like action is necessary to unblock the App Store review process for clients.
